package generate

import (
	"time"

	"github.com/sirupsen/logrus"
)

func costTime() func() {
	startTime := time.Now()

	return func() {
		logrus.Infof("costs %d ms", time.Now().Sub(startTime).Milliseconds())
	}
}

func WriteDoNotEdit() string {
	return "Code generated by go-gen DO NOT EDIT. visit https://github.com/goools/go-gen"
}
